# Generated by Django 3.2.8 on 2021-10-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField()),
                ('initial', models.CharField(help_text='inital product to update', max_length=200)),
                ('final', models.CharField(help_text='final product', max_length=200)),
                ('status', models.CharField(help_text='status of the update', max_length=200)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
